// Stub generated by Convex - will be replaced by `npx convex dev` / `npx convex codegen`
export const api: any = new Proxy({}, {
  get(_t, prop) {
    return new Proxy({}, { get(_t2, prop2) { return `${String(prop)}/${String(prop2)}`; } });
  }
});
export const internal: any = api;
